### PR TITLE
Sync with template repo

### PR DESCRIPTION
**Pull request by rosiemiller2**
### Description

Making sure that Mbed Build is up to date with all the latest changes in Mbed Tools Template.

### Test Coverage

- [ ]  This change is covered by existing or additional automated tests.
- [ ]  Manual testing has been performed (and evidence provided) as automated testing was not feasible.
- [x]  Additional tests are not required for this change (e.g. documentation update).

### CODE REVIEW

**Comment by rosiemiller2** [comment]
Hmm, I'm not sure how to tell codecov to chill about the coverage.

**Comment by muchzill4** [comment]
It won't prevent you from merging. Or shouldn't at least. 

I think `pre-commit` stuff is missing.

**Comment by rosiemiller2** [comment]
Ah is that not in the template yet? Darn

**Comment by muchzill4** [comment]
I think it is. https://github.com/ARMmbed/mbed-tools-template/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/.pre-commit-config.yaml

**Pull request merged**
